services:
  rabbitmq:
    image: rabbitmq:4.0-management  # 관리 UI가 포함된 버전
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"  # AMQP 프로토콜 포트
      - "15672:15672"  # 관리 UI 포트
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # 데이터 영속성 유지

volumes:
  rabbitmq_data:
    driver: local
